export const myProjects = [
  {
    id: 1,
    title: "Enyugma Website",
    description:
      "Official techno-cultural fest website of IIIT Bhagalpur, featuring events, registrations, results, and live updates.",
    subDescription: [
      "Developed the official website for Enyugma — IIIT Bhagalpur’s annual techno-cultural fest.",
      "Built the frontend using ReactJS and TailwindCSS for a visually engaging and responsive interface.",
      "Integrated Firebase for event registration, live leaderboards, and real-time updates.",
      "Handled backend APIs using Node.js & Express for event management and data processing.",
      "Collaborated closely with the organizing team to ensure smooth deployment and scalability during the fest.",
    ],
    href: "https://enyugma.iiitbh.ac.in/",
    logo: "",
    image: "/enyugma.png",
    tags: [
      { id: 1, name: "ReactJS", path: "/React.png" },
      { id: 2, name: "NodeJS", path: "/Node.png" },
      { id: 3, name: "Firebase", path: "/FireBase.png" },
      { id: 4, name: "TailwindCSS", path: "/Tailwind.png" },
      { id: 5, name: "JavaScript", path: "/JavaS.png" },
      { id: 6, name: "HTML", path: "/HTML.png" },
      { id: 7, name: "CSS", path: "/CSS.png" },
      { id: 8, name: "Figma", path: "/Figma.png" },
    ],
  },
  {
    id: 2,
    title: "OPCODE Website",
    description:
      "Open-source platform, a vibrant hub for collaborative development and innovation.",
    subDescription: [
      "Welcome to our open-source platform, a vibrant hub for collaborative development and innovation. Here, passionate individuals from diverse backgrounds converge to share, contribute, and enhance projects that drive positive change. Explore our repository of code, tools, and resources, and join us in shaping the future of technology together!",
    ],
    href: "https://opcode.gymkhana.iiitbh.ac.in/",
    logo: "",
    image: "/OPCODE.png",
    tags: [
      { id: 1, name: "ReactJS", path: "/React.png" },
      { id: 2, name: "NodeJS", path: "/Node.png" },
      { id: 3, name: "Firebase", path: "/FireBase.png" },
      { id: 4, name: "TailwindCSS", path: "/Tailwind.png" },
      { id: 5, name: "JavaScript", path: "/JavaS.png" },
      { id: 6, name: "HTML", path: "/HTML.png" },
      { id: 7, name: "CSS", path: "/CSS.png" },
      { id: 8, name: "Figma", path: "/Figma.png" },
    ],
  },
  {
    id: 3,
    title: "E-Summit Website",
    description:
      "Official website for IIIT Bhubaneswar’s annual entrepreneurship summit — showcasing events, registrations, and guests.",
    subDescription: [
      "Developed the complete frontend using ReactJS and TailwindCSS for a dynamic, responsive experience.",
      "Integrated Firebase for event registrations and real-time data updates.",
      "Built an admin dashboard for managing participants, sessions, and sponsors.",
      "Optimized SEO and performance for large visitor traffic during the summit.",
      "Collaborated with the E-Cell team to ensure brand consistency and smooth event flow.",
    ],
    href: "https://esummit.iiitbh.ac.in/",
    logo: "",
    image: "/esummit.png",
    tags: [
      { id: 1, name: "ReactJS", path: "/React.png" },
      { id: 2, name: "NodeJS", path: "/Node.png" },
      { id: 3, name: "Firebase", path: "/FireBase.png" },
      { id: 4, name: "TailwindCSS", path: "/Tailwind.png" },
      { id: 5, name: "JavaScript", path: "/JavaS.png" },
      { id: 6, name: "HTML", path: "/HTML.png" },
      { id: 7, name: "CSS", path: "/CSS.png" },
      { id: 8, name: "Figma", path: "/Figma.png" },
    ],
  },
  {
    id: 4,
    title: "Travel Website",
    description:
      "An AI-powered travel planning platform that helps users discover destinations, connect with travel buddies, and manage bookings seamlessly.",
    subDescription: [
      "Designed interactive wireframes and UI mockups in Figma for consistent, user-friendly design.",
      "Developed the frontend with ReactJS, Tailwind CSS, and JavaScript for a responsive, modern UI.",
      "Implemented secure authentication and database management using Firebase Auth and Firestore.",
      "Built APIs with Node.js and Express to handle trip planning, user profiles, and booking logic.",
      "Integrated payment systems and localization for global users.",
    ],
    href: "https://www.figma.com/proto/66Jp2iLshADjozuDD9AdMf/Untitled?node-id=40-5&t=SwIDCiS3EsfdA04C-1&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=97%3A2",
    logo: "",
    image: "/Tip2Trip.png",
    tags: [
      { id: 1, name: "ReactJS", path: "/React.png" },
      { id: 2, name: "NodeJS", path: "/Node.png" },
      { id: 3, name: "Firebase", path: "/FireBase.png" },
      { id: 4, name: "TailwindCSS", path: "/Tailwind.png" },
      { id: 5, name: "JavaScript", path: "/JavaS.png" },
      { id: 6, name: "HTML", path: "/HTML.png" },
      { id: 7, name: "CSS", path: "/CSS.png" },
      { id: 8, name: "Figma", path: "/Figma.png" },
    ],
  },
  {
    id: 5,
    title: "Love Babbar Code Help",
    description:
      "A coding help and discussion platform designed for learners and developers.",
    subDescription: [
      "Created UI mockups in Figma for structured layouts and responsive design planning.",
      "Built a ReactJS frontend with TailwindCSS for fast, responsive UI.",
      "Implemented role-based access with Firebase Auth (OAuth, JWT).",
      "Stored and managed data using Firebase Firestore.",
      "Enabled real-time discussion and notifications using Firebase Realtime Database.",
    ],
    href: "https://www.figma.com/proto/Mdr1zpjTPPQgT6mPoLQR4w/Untitled?node-id=1-2&t=QdRQXMpz1FGrr6uO-1&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1",
    logo: "",
    image: "/LoveBabbar.png",
    tags: [
      { id: 1, name: "ReactJS", path: "/React.png" },
      { id: 2, name: "TailwindCSS", path: "/Tailwind.png" },
      { id: 3, name: "Firebase", path: "/FireBase.png" },
      { id: 4, name: "JavaScript", path: "/JavaS.png" },
      { id: 5, name: "HTML", path: "/HTML.png" },
      { id: 6, name: "CSS", path: "/CSS.png" },
      { id: 7, name: "Figma", path: "/Figma.png" },
    ],
  },
  {
    id: 6,
    title: "Gym App",
    description:
      "A fitness tracking web app to monitor workouts, progress, and nutrition plans.",
    subDescription: [
      "Designed user dashboards and fitness tracking screens in Figma for clarity and usability.",
      "Developed using ReactJS + Tailwind CSS for sleek UI and responsive dashboards.",
      "Built backend APIs with Node.js & Express for user profiles and workout logs.",
      "Integrated Firebase Auth for secure login and Firestore for storing progress.",
      "Added charts and analytics using Chart.js for visualizing workout history.",
    ],
    href: "https://niceasy.netlify.app/",
    logo: "",
    image: "/Gym.png",
    tags: [
      { id: 1, name: "ReactJS", path: "/React.png" },
      { id: 2, name: "NodeJS", path: "/Node.png" },
      { id: 3, name: "Firebase", path: "/FireBase.png" },
      { id: 4, name: "TailwindCSS", path: "/Tailwind.png" },
      { id: 5, name: "JavaScript", path: "/JavaS.png" },
      { id: 6, name: "HTML", path: "/HTML.png" },
      { id: 7, name: "CSS", path: "/CSS.png" },
      { id: 8, name: "Figma", path: "/Figma.png" },
    ],
  },
  {
    id: 7,
    title: "Restaurant Website",
    description:
      "A modern restaurant website with online ordering, reservations, and menu management.",
    subDescription: [
      "Prototyped the design and user flow in Figma for responsive and aesthetic layouts.",
      "Built a clean UI with HTML, CSS, JavaScript, and TailwindCSS.",
      "Developed a ReactJS frontend for interactive menu browsing and ordering.",
      "Integrated Firebase for authentication, orders, and real-time reservation updates.",
      "Backend APIs developed with Node.js & Express for menu and cart management.",
    ],
    href: "https://drive.google.com/file/d/1tMZkRddxpa9IA8RGvMx_sY9wvTDpYrCY/view?usp=sharing",
    logo: "",
    image: "/Restt.png",
    tags: [
      { id: 1, name: "ReactJS", path: "/React.png" },
      { id: 2, name: "NodeJS", path: "/Node.png" },
      { id: 3, name: "Firebase", path: "/FireBase.png" },
      { id: 4, name: "TailwindCSS", path: "/Tailwind.png" },
      { id: 5, name: "JavaScript", path: "/JavaS.png" },
      { id: 6, name: "HTML", path: "/HTML.png" },
      { id: 7, name: "CSS", path: "/CSS.png" },
      { id: 8, name: "Figma", path: "/Figma.png" },
    ],
  },
  
];




export const experiences = [
  {
    title: "UI/UX Lead & Frontend Developer",
    job: "DevC – IIIT Bhagalpur Development Club",
    date: "Sep 2025 – Present",
    contents: [
      "Leading the design and frontend development of IIIT Bhagalpur’s in-house projects and websites.",
      "Created and maintained the design system for DevC projects using Figma and TailwindCSS.",
      "Collaborating with developers to ensure seamless UI implementation and consistent branding.",
      "Developed reusable React.js components, improving scalability and maintainability across projects.",
      "Mentored junior members in UI/UX principles, frontend workflows, and modern design tools.",
    ],
  },
  {
    title: "UI/UX & Social Media Marketing Intern",
    job: "Wisonlect",
    date: "Jul 2025 – Sep 2025",
    contents: [
      "Developed responsive UI components using React.js and TailwindCSS for improved scalability.",
      "Conducted usability testing and implemented feedback loops to refine product workflows.",
      "Optimized social media creatives using Figma and Adobe Illustrator, improving engagement by ~25%.",
      "Collaborated with the back-end team to integrate REST APIs seamlessly into the front-end.",
      "Automated marketing content scheduling using third-party APIs and reduced manual workload.",
    ],
  },
  {
    title: "UI/UX Designer and Frontend Developer",
    job: "Tip2Trip",
    date: "Jul 2025 – Present",
    contents: [
      "Designed low-fidelity wireframes and interactive prototypes in Figma for new product features.",
      "Built and deployed modular, reusable React.js components with optimized state management.",
      "Enhanced application performance by implementing lazy loading and code-splitting techniques.",
      "Integrated Google Maps API and third-party services to enhance travel planning features.",
      "Ensured cross-browser compatibility and WCAG accessibility compliance across platforms.",
    ],
  },
  {
    title: "Social Media and Design Lead",
    job: "Indian Institute of Information Technology Bhagalpur",
    date: "Feb 2024 – Aug 2025",
    contents: [
      "Directed a 10+ member creative team, managing design workflows with Agile methodology.",
      "Developed UI/UX assets for institute web portals using Figma, Photoshop, and Illustrator.",
      "Implemented social media automation workflows with Buffer and Zapier, reducing manual effort.",
      "Analyzed campaign analytics (Meta Business Suite, LinkedIn Insights) to optimize engagement rates.",
      "Collaborated with developers to integrate branding assets into institute’s web applications.",
    ],
  },
  {
    title: "SDE Intern",
    job: "Li-Mat Soft Solutions Pvt Ltd",
    date: "Feb 2025 – Apr 2025",
    contents: [
      "Contributed to back-end services using Node.js and Express.js for scalable APIs.",
      "Worked on software infrastructure improvements, debugging performance bottlenecks in production.",
      "Implemented authentication & authorization workflows using JWT and OAuth standards.",
      "Integrated MySQL database queries with optimized indexing strategies for faster responses.",
      "Wrote unit tests with Jest and Mocha to improve code coverage and ensure reliability.",
    ],
  },
];
